### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by rohitkayako** [scrollback/scrollback#501]
installation not working properly installed many dependencies manually.

64  npm install ebus
   65  npm install pg
   66  npm install secure-random
   67  npm install request
   68  npm install redis
   69  npm install objectlevel
   70  npm install underscore
   71  npm install htmlencode
   72  npm install twit
   73  npm install jade
   74  npm install elasticsearch
   75  npm install sockjs
   76  npm install express

![screenshot from 2015-02-14 21 05 23](https://cloud.githubusercontent.com/assets/6542189/6200072/6ac64908-b48d-11e4-9362-c71962cd7b39.png)

and no css or js

**Comment by pyadav** [comment]
@rohitkayako ya i know there are some problem which enforce you to install package dependencies manually.

*To overcome with Installation do this* ::
- Install package dependencies manually if you have to.
- Run 
```
gulp
```
before running 
```
npm start OR  node index.js

```
which will solve your problem of no **css or js** because these are build by **gulp**

**Comment by aravindet** [comment]
@sindhus could you take a look at this?

**Comment by sindhus** [comment]
yep, on it.

**Comment by sindhus** [comment]
@rohitkayako We've updated the package.json. Give it a try!
