### ISSUE TITLE
feedbacks from use

### ISSUE THREAD

**Issue by jeancharlesamey** [scrollback/scrollback#510]
Hi all,

We (TEDxReims) have tested scrollback.io during 2 hours last week (www.scrollbacl.io/TEDxReims) I collected few feedback from users, I would like to share them with you, because it seems they is a lot of opportunity to improve the whole experience.

- Impossible to see if someone is writting a message, so if we are waiting an answer to question, in one, two or three times.
- Impossible to set avatar if register with an email adress.
- Impossible to change username without register
- Long messages are truncated
- What spam option do is not clear (maybe clarify in setup) one friend (the animator of the discussion) long messages had been detected as spam... not cool. I speak to him today, we came with the idea to be able (as admin) to define people as no spammer (even if they write a lot)
- After the event a lot of fantoms seems still connected to the room, and today register persons seems here, it's not clear why (http://www.clipular.com/c/5473659163508736.png?k=XhnegVYuW1xEmnDb3t_KzjIRSu0)
- At the end of an event like this, it would be nice to be able to close the discussion, with a bolder style in order to invite people to leave, maybe also the option to close the discussion till the next.

Best regards
Have a nice day,

J.

**Comment by aravindet** [comment]
Thank you for trying out Scrollbak and thanks for the valuable feedback!

We will try to add these to the next versions of the product.

**Comment by aravindet** [comment]
To clarify a couple of features (we could certainly do with more obvious UI):
- The moderation tools block messages if 
  1. too many messages by the same user within 60s
  2. same message is repeated multiple times
  3. message contains abusive words (english); this can be turned off by the administrator in room configurations. I think this might be what happened. The error message should explain why the message was blocked.

- The gray-colored user avatars are offline followers - people who followed the room by clicking the "star" icon but are not online right now. They will get email summary every day. In the next version they will be shown under a heading "Offline".

- Extremely long messages are truncated at 4 lines in the UI, but clicking on it will expand it so you can read the whole message.

- If you register with an email address, we take the avatar from gravatar.com — you can change it there. However this might not be clear, and we are planning an upload your avatar feature.

The other suggested features are not supported now:

- Showing "someone is replying..." while they are typing
- Changing username without registering
- Closing a chat room so that there are no more messages

**Comment by jeancharlesamey** [comment]
Thanks for your feedback, Please allow me to answer.

. what if the administrator will have the power to set UNspam user. For example, in our case, our expert guest was answering a lot, within 60s, so we had to unspam the all chatroom (risky buisness), it would have been nice to unspam just that person.
. the same way with long messages, people on the chatroom had to expand the answer of our expert (answering by long messages) what if some account will be auto-expandable ?
. to the first two points, the solution is maybe a concept of trusted accounts, that will be trusted and allow to post long auto-expandable messages without any restriction of time.
. setting an avatar without gravatar would be super nice, you know it ! as nice as changing name whitout register.
. heading "offline" will more clear

Best regards
Have a nice day
.
