### ISSUE TITLE
Syntax error in tools/install.sh says unexpected token

### ISSUE THREAD

**Issue by jdoexyz100** [scrollback/scrollback#617]
Hello. I'm trying to install scrollback on my Ubuntu server hosted on Digital Ocean, but I receive this error:

./install.sh: line 279: syntax error near unexpected token `"Creating DB user and Scrollback DBs..."'
./install.sh: line 279: `    printf("Creating DB user and Scrollback DBs...")'

It doesn't finish the installation process it does not open the service on http://localhost:7528.

The command I used to try to install scrollback was: wget https://raw.githubusercontent.com/scrollback/scrollback/master/tools/install.sh -O install.sh && chmod +x install.sh && ./install.sh

Important: The title of this issue displays the true error message. For some reason ticks are not showing up in this text field.

**Comment by aravindet** [comment]
@jdoexyz100 what's your bash version? It requires bash 4. @sindhus could you comment?

**Comment by sindhus** [comment]
@jdoexyz100 Thanks for reporting this. Issue fixed in 67fd95c0aa70d2eae7746065a9036935ff337f90. Try again, please!

**Comment by xyz99** [comment]
I ran this and received the same error. Could it be because postgres_osx_create() was changed and not postgres_create_linux()?  I am using Ubuntu which should be based on Linux I believe? I'm not using OSX. Thank you for your help so far : 
wget https://raw.githubusercontent.com/scrollback/scrollback/master/tools/install.sh -O install.sh && chmod +x install.sh && ./install.sh

**Comment by sindhus** [comment]
Oops sorry! Will fix this asap.
