### ISSUE TITLE
User menu poorly positioned on iOS Safari landscape mode

### ISSUE THREAD

**Issue by mengwong** [scrollback/scrollback#754]
box says CHANGE USERNAME Sign Up.

Tapping Change Username doesn't do anything.

Tapping Sign Up just says Report Issue.

**Comment by aravindet** [comment]
Thanks! Confirmed: on landscape mode the popover menu position is incorrect; all items apart from "Report Issue" are placed outside the top edge of the screen. This should be an easy fix @satya164 

Creating another issue for the confusing UI ("Change username" looks like a button; it's supposed to be text that suggests that the user sign in, in order to change their username.)

**Comment by aravindet** [comment]
Should be in production in about an hour.
