### ISSUE TITLE
Add moderation

### ISSUE THREAD

**Issue by jeans** [scrollback/scrollback#787]
As a chat operator, I want to be able to moderate the chat (ban or mute users, delete messages)

**Comment by aravindet** [comment]
Thanks! Both banning users and deleting messages are already available.

**Why you might not be able to see these options**
- You should be signed into scrollback as the room owner in order to see these options. To check this, see if it says “(owner)” next to your name in the right sidebar (“people sidebar”)
- Instead of “delete”, we call it “hide”. Other than room owner, no one can ever see hidden messages. We don't delete messages outright, in case you change your mind and wish to show them again later.
- If your room configuration allows guests to post messages, the ban option will not be available. (Otherwise when you ban someone they can just sign out and come back as a guest). To change these configurations, go to your room, click "Configure room" and then click “Permissions”. The “Who can post?” option should be either “Logged in users” or “Followers”.

*Note: If you use IRC or Twitter integration, you must allow guests to post messages, and ban functionality will not be available to you. (This is because users coming from IRC and Twitter are considered guests in the Scrollback system.) For the moment you have to choose between the ability to ban users or Twitter/IRC integration. We’re working on a fix*

**How to use moderation features**
- To hide a message, click the message and a menu will pop up with the Hide option.
- To hide an entire discussion, click the overflow icon (three dots) on the top right corner to see the menu.
- To ban a user, click the user you wish to ban in the right sidebar and a menu will appear. You may have to click the “people” icon (two people) in the toolbar to show the sidebar if you're on mobile.
